language: cpp
os:
  - osx
  - linux

osx_image: xcode7.2b3

dist: trusty
sudo: required

env:
  global:
  # Coverity
   - secure: "qu69N1nyTl2TPAMQKSW7gnHFNiTpKGs+xLIl6pGZp28HtLsI+ejeQD2FuVcN2w8RUpUSWL7VBHXtSrEN0ByM2UJ2JSYaEdNyLH0aOt0irDLfUciNhIkG02oY1/pIL+e5+CwB/rsk19Bai6Q9VKJDNnM0WFV4fLvMMDOKFXuncKU="
   - COVERITY_SCAN_BUILD_COMMAND="make -j2"
   - COVERITY_SCAN_PROJECT_NAME="OSSIA/i-score"
   - COVERITY_SCAN_NOTIFICATION_EMAIL="jeanmichael.celerier@gmail.com"
   - COVERITY_SCAN_BRANCH_PATTERN="master"
   - COVERITY_SCAN_BUILD_URL="https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
   - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"

# TODO : DEPLOYMENT=False & Release ?
matrix:
  exclude:
    - os: linux
    - os: osx

  include:
  # GCOV
    - os: linux
      env: BUILD_TYPE=Debug   STATIC_PLUGINS=False DEPLOYMENT=False CAN_DEPLOY=False USE_COVERITY=False STATIC_QT=False USE_GCOV=True

    - os: osx
      env: BUILD_TYPE=Release STATIC_PLUGINS=True  DEPLOYMENT=True  CAN_DEPLOY=True  USE_COVERITY=False STATIC_QT=False USE_GCOV=False
    - os: linux
      env: BUILD_TYPE=Release STATIC_PLUGINS=True  DEPLOYMENT=True  CAN_DEPLOY=True  USE_COVERITY=False STATIC_QT=True  USE_GCOV=False

    - os: osx
      env: BUILD_TYPE=Debug   STATIC_PLUGINS=False DEPLOYMENT=False CAN_DEPLOY=False USE_COVERITY=False STATIC_QT=False USE_GCOV=False
    - os: osx
      env: BUILD_TYPE=Debug   STATIC_PLUGINS=True  DEPLOYMENT=False CAN_DEPLOY=False USE_COVERITY=False STATIC_QT=False USE_GCOV=False
    - os: osx
      env: BUILD_TYPE=Release STATIC_PLUGINS=False DEPLOYMENT=True  CAN_DEPLOY=False USE_COVERITY=False STATIC_QT=False USE_GCOV=False

    - os: linux
      env: BUILD_TYPE=Debug   STATIC_PLUGINS=False DEPLOYMENT=False CAN_DEPLOY=False USE_COVERITY=False STATIC_QT=False USE_GCOV=False
    - os: linux
      env: BUILD_TYPE=Debug   STATIC_PLUGINS=True  DEPLOYMENT=False CAN_DEPLOY=False USE_COVERITY=False STATIC_QT=False USE_GCOV=False
    - os: linux
      env: BUILD_TYPE=Release STATIC_PLUGINS=False DEPLOYMENT=True  CAN_DEPLOY=False USE_COVERITY=False STATIC_QT=False USE_GCOV=False

# Coverity
#    - os: linux
#      env: BUILD_TYPE=Debug     STATIC_PLUGINS=False DEPLOYMENT=False CAN_DEPLOY=False USE_COVERITY=True STATIC_QT=False

before_install:
- "./tools/travis/deps.sh"

script:
- "./tools/travis/build.sh"

after_success:
- "./tools/travis/deploy.sh"

deploy:
  - provider: releases
    api_key:
      secure: "hk56wIhJMippWajLTGtO44szXtBCzhCNHAET9fKZ7dXcfEVG22YHuUDMo1ROn6ZhthB5m8SLgctuTf4GtuvGxhdQzjeBSsvYCs6QAAUtMjBb4/lafcBZfr3Amf5TT8MfznGESQDMGjMUjnwQlUoWCVE0XoqNq6DbFlyoZPpscSE="
    file: build/i-score-$TRAVIS_TAG-OSX.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $CAN_DEPLOY = True && $TRAVIS_OS_NAME = osx
  - provider: releases
    api_key:
      secure: "hk56wIhJMippWajLTGtO44szXtBCzhCNHAET9fKZ7dXcfEVG22YHuUDMo1ROn6ZhthB5m8SLgctuTf4GtuvGxhdQzjeBSsvYCs6QAAUtMjBb4/lafcBZfr3Amf5TT8MfznGESQDMGjMUjnwQlUoWCVE0XoqNq6DbFlyoZPpscSE="
    file: build/i-score-$TRAVIS_TAG-Ubuntu-14.04-amd64.deb
    skip_cleanup: true
    on:
      tags: true
      condition: $CAN_DEPLOY = True && $TRAVIS_OS_NAME = linux
