language: cpp
install:
  - sudo add-apt-repository ppa:packetlost/cmake
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install cmake3  qtbase-opensource-src

script: 
  - cmake . 
  - make install
