language: cpp

os:
  - osx
  - linux

osx_image: xcode6.4

before_install:
- "./tools/travis/deps.sh"

script:
- "./tools/travis/build.sh"

after_success:
- "./tools/travis/deploy.sh"

deploy:
  - provider: releases
    api_key:
      secure: "hk56wIhJMippWajLTGtO44szXtBCzhCNHAET9fKZ7dXcfEVG22YHuUDMo1ROn6ZhthB5m8SLgctuTf4GtuvGxhdQzjeBSsvYCs6QAAUtMjBb4/lafcBZfr3Amf5TT8MfznGESQDMGjMUjnwQlUoWCVE0XoqNq6DbFlyoZPpscSE="
    file: build/i-score-$TRAVIS_TAG-OSX.zip
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
