language: cpp
install:
  - sudo add-apt-repository ppa:packetlost/cmake -y
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake3  qtbase-opensource-src g++-4.9

script: 
  - cmake . 
  - make install
