clone_depth: 1

environment:
  QTDIR: C:\Qt\5.4\mingw491_32
  MINGW: C:\Qt\Tools\mingw491_32

configuration: Release

install:
  - choco install -y nsis cmake.portable
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin;C:\Qt\Tools\QtCreator\bin
  
  
build_script:
  - mkdir build
  - cd build
  - cmake.exe -G"MinGW Makefiles" -DISCORE_STATIC_PLUGINS:Bool=True -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_MAKE_PROGRAM=mingw32-make.exe -DCMAKE_PREFIX_PATH="C:/Qt/5.4/mingw491_32/lib/cmake/Qt5" -DBOOST_DIR="C:/Libraries/boost" --build ..
