clone_depth: 1

environment:
  QTDIR: C:\Qt\5.4\mingw491_32
  MINGW: C:\Qt\Tools\mingw491_32
  BOOST_ROOT: c:\Libraries\boost
  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib
  
configuration: Release

install:
  - choco install -y nsis cmake.portable
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin;C:\Qt\Tools\QtCreator\bin
  
build_script:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -G"MinGW Makefiles" -DISCORE_STATIC_PLUGINS:Bool=True -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_MAKE_PROGRAM=mingw32-make.exe -DCMAKE_PREFIX_PATH="C:/Qt/5.4/mingw491_32/lib/cmake/Qt5" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ..
  - cmake --build .
